# Generated by Django 6.0.5 on 2026-05-23 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("name_en", models.CharField(max_length=100, null=True, unique=True)),
                ("name_fa", models.CharField(max_length=100, null=True, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_fa", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("name_en", models.CharField(max_length=50, null=True, unique=True)),
                ("name_fa", models.CharField(max_length=50, null=True, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("title_en", models.CharField(max_length=200, null=True)),
                ("title_fa", models.CharField(max_length=200, null=True)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("description", models.TextField()),
                ("description_en", models.TextField(null=True)),
                ("description_fa", models.TextField(null=True)),
                (
                    "github_url",
                    models.URLField(blank=True, help_text="GitHub repository URL"),
                ),
                ("demo_url", models.URLField(blank=True, help_text="Live demo URL")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                ("featured", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="projects", to="blog.tag"
                    ),
                ),
            ],
            options={
                "ordering": ["-featured", "order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("title_en", models.CharField(max_length=250, null=True)),
                ("title_fa", models.CharField(max_length=250, null=True)),
                ("slug", models.SlugField(blank=True, max_length=250, unique=True)),
                (
                    "excerpt",
                    models.TextField(help_text="Short description", max_length=500),
                ),
                (
                    "excerpt_en",
                    models.TextField(
                        help_text="Short description", max_length=500, null=True
                    ),
                ),
                (
                    "excerpt_fa",
                    models.TextField(
                        help_text="Short description", max_length=500, null=True
                    ),
                ),
                ("content", models.TextField(help_text="Markdown content")),
                (
                    "content_en",
                    models.TextField(help_text="Markdown content", null=True),
                ),
                (
                    "content_fa",
                    models.TextField(help_text="Markdown content", null=True),
                ),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                (
                    "meta_description_en",
                    models.CharField(blank=True, max_length=160, null=True),
                ),
                (
                    "meta_description_fa",
                    models.CharField(blank=True, max_length=160, null=True),
                ),
                ("meta_keywords", models.CharField(blank=True, max_length=250)),
                (
                    "meta_keywords_en",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "meta_keywords_fa",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "featured_image",
                    models.ImageField(blank=True, null=True, upload_to="posts/%Y/%m/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "read_time",
                    models.IntegerField(
                        default=5, help_text="Estimated reading time in minutes"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="blog.category",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="posts", to="blog.tag"
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-published_at"], name="blog_post_publish_2c9212_idx"
                    ),
                    models.Index(fields=["slug"], name="blog_post_slug_cdb902_idx"),
                ],
            },
        ),
    ]
